import './globals.css';
import type { Metadata } from 'next';
import { Kalam } from 'next/font/google';

const kalam = Kalam({ subsets: ['devanagari'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kalam.className}>
        <header className="p-3 border-b border-zinc-700 mb-2">
          <h1 className="text-yellow-500 text-4xl">Barganha</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
