import './globals.css';
import type { Metadata } from 'next';
import { Kalam, Inter } from 'next/font/google';

const kalam = Kalam({ subsets: ['devanagari'], weight: ['400', '700'] });

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-3 border-b border-zinc-700 mb-2">
          <div className="max-w-xl flex justify-center">
            <h2 className={`${kalam.className} text-yellow-500 text-4xl`}>
              Barganha
            </h2>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
